version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: swift_task
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - swift_network

  go-app:
    build: .
    container_name: swift_app
    environment:
      - DB_HOST=db
      - DB_NAME=swift_task
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - DB_PORT=5432
      - DATA_FILE_PATH=/app/data/swift-codes.csv
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    networks:
      - swift_network

volumes:
  postgres_data:

networks:
  swift_network:
    driver: bridge
